### ISSUE TITLE
invalid pulse data length

### ISSUE THREAD

**Issue by bvdbos** [athombv/nl.kpn.ir#2]
Forced kpn.ir on 1.3.2 and installed fine, could add device but got an invalid pulse data error when ttrying to use the app. Could be caused by 1.3.2 instead of 1.5.x ?

`Stack trace:

Error: Invalid pulse data length, should be odd.
at Object.reviver (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:70:17)
at Object.parse (native)
at jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:58:15)
at Array.map (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:1231)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)
at internal/child_process.js:729:12
at nextTickCallbackWith0Args (node.js:489:9)
at process._tickCallback (node.js:418:13)

Exit code: 1
Exit signal: null`

**Comment by BasKiers** [comment]
Hi,

It is indeed the case that the app requires Homey version 1.5 because of the above stack trace. 

Regards,
Bas
